wpena.lucasian/Models/Banco.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace wpena.lucasian.Models
{
    public class Banco
    {
        public int id { get; set; }
        public string nombre { get; set; }
    }
}

wpena.lucasian/Models/BancoCuentas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace wpena.lucasian.Models
{
    public class BancoCuentas
    {
        public Banco banco { get; set; }
        public Cuenta cuenta { get; set; }
        public List<Cuenta> cuentas { get; set; }
    }
}

wpena.lucasian/Models/Cuenta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace wpena.lucasian.Models
{
    public class Cuenta
    {
        public int id { get; set; }
        public string nombre { get; set; }
    }
}

wpena.lucasian/Controllers/BancoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using wpena.lucasian.Services;

namespace wpena.lucasian.Controllers
{
    public class BancoController : Controller
    {
        // GET: Banco
        public ActionResult Index()
        {
            return View(BancoRepositorio.Bancos.Select(x => x.banco));
        }

        // GET: Banco/Details/5
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var model = BancoRepositorio.Bancos.Find(x => x.banco != null && x.banco.id == id);

            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }
    }
}

wpena.lucasian/Controllers/BancoCuentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using wpena.lucasian.Models;
using wpena.lucasian.Services;

namespace wpena.lucasian.Controllers
{
    [RoutePrefix("api/banco")]
    public class BancoCuentasController : ApiController
    {
        // GET: api/Banco
        [HttpGet]
        public IEnumerable<Banco> obtenerBancos()
        {
            return BancoRepositorio.Bancos.Select(x => x.banco);
        }

        // GET: api/Banco/5
        [HttpGet]
        public Banco obtenerBancos(int id)
        {
            if (BancoRepositorio.Bancos.Any(x => x.banco != null && x.banco.id == id))
            {
                return BancoRepositorio.Bancos.Find(x => x.banco != null && x.banco.id == id).banco;
            }
            else
            {
                return null;
            }
        }

        // POST: api/Banco
        [HttpPost]
        public ApiRespuesta crearBanco([FromBody]string Nombre)
        {
            try
            {
                Banco banco = new Banco() { nombre = Nombre };
                BancoRepositorio.confirmarBanco(banco);
                return new ApiRespuesta()
                {
                    status = "ok",
                    message = "registro ok",
                    id = banco.id
                };
            }
            catch (Exception ex)
            {
                return new ApiRespuesta()
                {
                    status = "error",
                    message = ex.Message
                };
            }
        }

        // PUT: api/Banco/5
        [HttpPut]
        public ApiRespuesta actualizarBanco(int id, [FromBody]Banco Banco)
        {
            try
            {
                BancoRepositorio.confirmarBanco(Banco, "U", id);
                return new ApiRespuesta()
                {
                    status = "ok",
                    message = "registro ok",
                    id = Banco.id
                };
            }
            catch (Exception ex)
            {
                return new ApiRespuesta()
                {
                    status = "error",
                    message = ex.Message
                };
            }
        }

        // DELETE: api/Banco/5
        [HttpDelete]
        public ApiRespuesta eliminarBanco(int id)
        {
            try
            {
                Banco banco = new Banco();
                BancoRepositorio.confirmarBanco(banco, "D", id);
                return new ApiRespuesta()
                {
                    status = "ok",
                    message = "registro ok",
                    id = banco.id
                };
            }
            catch (Exception ex)
            {
                return new ApiRespuesta()
                {
                    status = "error",
                    message = ex.Message
                };
            }
        }

        // GET: api/Banco/cuenta
        [Route("{id_banco:int}/cuenta")]
        [HttpGet]
        public IEnumerable<Cuenta> obtenerCuentas(int id_banco)
        {
            if (BancoRepositorio.Bancos.Any(x => x.banco.id == id_banco))
            {
                return BancoRepositorio.Bancos.Find(x => x.banco.id == id_banco).cuentas;
            }
            else
            {
                return new List<Cuenta>();
            }
        }

        // GET: api/Banco/5/cuenta/3
        [Route("{id_banco:int}/cuenta/{id:int}")]
        [HttpGet]
        public Cuenta obtenerCuenta(int id_banco, int id)
        {
            if (BancoRepositorio.Bancos.Any(x => x.banco.id == id_banco))
            {
                return BancoRepositorio.Bancos.Find(x => x.banco.id == id_banco).cuentas.Find(x => x.id == id) ?? new Cuenta();
            }
            else
            {
                return null;
            }
        }

        // POST: api/Banco/cuenta
        [Route("{id_banco:int}/cuenta")]
        [HttpPost]
        public ApiRespuesta crearCuenta(int id_banco, [FromBody]string Nombre)
        {
            try
            {
                Cuenta cuenta = new Cuenta() { nombre = Nombre };
                BancoRepositorio.confirmarCuenta(id_banco, cuenta);
                return new ApiRespuesta()
                {
                    status = "ok",
                    message = "registro ok",
                    id = cuenta.id
                };
            }
            catch (Exception ex)
            {
                return new ApiRespuesta()
                {
                    status = "error",
                    message = ex.Message
                };
            }
        }

        // PUT: api/Banco/5/cuenta/3
        [Route("{id_banco:int}/cuenta/{id:int}")]
        [HttpPut]
        public ApiRespuesta actualizarCuenta(int id_banco, int id, [FromBody]Cuenta cuenta)
        {
            try
            {
                BancoRepositorio.confirmarCuenta(id_banco, cuenta, "U", id);
                return new ApiRespuesta()
                {
                    status = "ok",
                    message = "registro ok",
                    id = cuenta.id
                };
            }
            catch (Exception ex)
            {
                return new ApiRespuesta()
                {
                    status = "error",
                    message = ex.Message
                };
            }
        }

        // DELETE: api/Banco/5/cuenta/3
        [Route("{id_banco:int}/cuenta/{id:int}")]
        [HttpDelete]
        public ApiRespuesta eliminarCuenta(int id_banco, int id)
        {
            try
            {
                Cuenta cuenta = new Cuenta();
                BancoRepositorio.confirmarCuenta(id_banco, cuenta, "D", id);
                return new ApiRespuesta()
                {
                    status = "ok",
                    message = "registro ok",
                    id = cuenta.id
                };
            }
            catch (Exception ex)
            {
                return new ApiRespuesta()
                {
                    status = "error",
                    message = ex.Message
                };
            }
        }

        /// <summary>
        /// clase de respuesta
        /// </summary>
        public class ApiRespuesta
        {
            public string status { get; set; }
            public string message { get; set; }
            public int? id { get; set; }
        }
    }
}

wpena.lucasian/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace wpena.lucasian.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

wpena.lucasian/Views/Banco/Details.cshtml
@model wpena.lucasian.Models.BancoCuentas

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Banco</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.banco.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.banco.nombre)
        </dd>

    </dl>
    <h4>Cuentas</h4>
    <table class="table">

        @if (Model.cuentas.Any())
        {
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.cuenta.nombre)
                </th>
            </tr>
            foreach (var item in Model.cuentas)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nombre)
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td>
                    No se encontraron cuentas asociadas al banco
                </td>
            </tr>
        }
    </table>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

wpena.lucasian/Views/Banco/Index.cshtml
@model IEnumerable<wpena.lucasian.Models.Banco>

@{
    ViewBag.Title = "Inicio";
}

<h2>Inicio</h2>

<table class="table">
    @if (Model.Any())
    {
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th></th>
        </tr>

        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.id })
                </td>
            </tr>
        }
    }
    else
    {
        <tr>
            <td>
                No se encontraron bancos registrados.
            </td>
        </tr>
    }



</table>

wpena.lucasian/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

wpena.lucasian/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

wpena.lucasian/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

wpena.lucasian/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WPENA.LUCASIAN", "Index", "Banco", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WPENA ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>